# Process config example for arXiv dataset

# global parameters
project_name: 'arXiv'
dataset_path: '/export/project/LLMData/RedPajama/arxiv'  # path to your dataset directory or file
np: 4  # number of subprocess to process your dataset


export_path: '/export/project/lijiawei421/projects/innohk/data_juicer/profiling_dj_on_RedPajama/RedPajama_arxiv_processed_by_dj_v2.jsonl'

# process schedule
# a list of several process operators with their arguments
process:
  - remove_header_mapper:
      drop_no_head: true
  - remove_comments_mapper:
      doc_type: ['md', 'tex']
      inline: true
      multiline: true
  - remove_bibliography_mapper:
  - expand_macro_mapper:
  - text_length_filter:
      min_len: 1
